### ISSUE TITLE
'for loop' docs

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#1]
On page https://c3lang.github.io/c3docs/examples/ it says:

> the for-loop is the same as C99

Does that mean support for C features like:

`for (int x = 1, y = 2; x < 10; ++x, y += 2) { ... }
`

Comma operator was said to be removed from the language. `For` could be made simpler, too.

**Comment by lerno** [comment]
In fact it goes further than C99. This is valid:

```
for (int i = 0, Foo foo = { 3 }, Bar bar; i < foo.i; i++, bar.x = test()) { ... }
```

**Comment by lerno** [comment]
This does not appear to be an issue, so I close it.
