### ISSUE TITLE
Various issues that we were discussing on Discord

### ISSUE THREAD

**Issue by jamestmartin** [c3lang/c3docs#14]
1. The Undefined Behavior page uses comparison between `short` and `ushort` as undefined behavior that triggers a trap, but it *is* defined, as `s < 0 || u > (ushort) s`.

2. The Conversions page claims there is an implicit conversion from `double` to `float`, but there actually isn't.

3. The Conversions page claims there is an implicit conversion from `float` to `bool` (actually *twice* in the same list), but this behavior only applies to conditionals (which it does not say), and the same behavior also applies to other types, but you do not say that either.

4. The Changes from C page only mentions the difference in integer conversions, but not the difference in floating-point conversions (i.e. that double isn't implicitly converted to float).

5. Macros
   ```c
   macro @square(x) { return x * x } // missing semicolon
   ```

6. Undefined Behavior: Pre and post conditions says that "violating either pre or post conditions is considered undefined behaviour", but the undefined behavior page doesn't.

7. Crazy Ideas: "Same reasoing as arrays." -- should be "reasoning"

8. Crazy Ideas: "No, add the '$' symbol to introduce hygienic temporaries" -- should be "now"

9. About C3: "Bas van der Berg (Author of C2" -- missing a closing parenthesis

10. Setup: "C3 is ready for end users yet," -- "C3 is *not* ready for end users yet,"

11. Setup: LLVM installation doesn't mention that installing through `apt` works fine too, though I don't know if you actually care to mention that.

12. Contribute: "Currently C3 is being designed it means that there is no complete compiler yet" -- Maybe "C3 is currently in the design phase, *which means that* there is no complete compiler yet"? There are other ways to fix that sentence, but it's ungrammatical as-is.

13. Changelog: "Current revision made 2020-03-29." -- This is technically grammatically correct, but awkward IMO. Maybe "This documentation was most recently revised on 2020-03-29" or something? Anyway, that's just nitpicking, so feel free to ignore it.

**Comment by lerno** [comment]
Fixed in the latest revision 2020-03-20
