### ISSUE TITLE
Inconsistent whitespace definition

### ISSUE THREAD

**Issue by flysand7** [c3lang/c3docs#17]
![image](https://user-images.githubusercontent.com/27109464/125346815-e8d03400-e3a5-11eb-802a-671ee6e677c9.png)

CR character is `\r`, however it is not listed in definition below.

`\f` is a form-feed character, however it is not listed in the text above the definition.

`\v` is a vertical tab character, however it is not listed in the text above the definition.

**Comment by lerno** [comment]
This should be fixed now.
