### ISSUE TITLE
Error on code formatting in "Your First Project" page

### ISSUE THREAD

**Issue by giluis** [c3lang/c3docs#19]
Hi, I believe there is misformatting of the code in "Your First Project" page.
Under "A real project" header, 
![image](https://user-images.githubusercontent.com/52404649/131467737-be60e4fb-259f-47ee-aba6-86c1c021c3d6.png)
In my estimation, perhaps the "init" should be rendered as code as well.

**Comment by lerno** [comment]
Thank you, I'll have a look.

**Comment by lerno** [comment]
This should be updated and ok now.
