### ISSUE TITLE
Macros page contains reference to removed `@escape` attribute

### ISSUE THREAD

**Issue by Emily-TTG** [c3lang/c3docs#29]
http://www.c3-lang.org/macros/ contains the following snippet:
![Screenshot 2022-10-06 at 12 24 38](https://user-images.githubusercontent.com/80696589/194300778-91cd84a7-ff41-4eb2-8276-b23af7d6062f.png)
Wherein the now-removed `@escape` attribute is shown.

This should probably be removed for the sake of clarity.

**Comment by Its-Kenta** [comment]
Looks like that got fixed judging by the change.

**Comment by lerno** [comment]
Yep, that is fixed
