### ISSUE TITLE
noreturn attribute

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#3]
This attribute could be handled by assert:

```
void foo()
{
  for (;;) { }

  assert(false);
}
```

which will also show possible error.

**Comment by lerno** [comment]
The downside is that the information is not available in the function signature, but requires reading the code. It also then does not become a strict contract. So it is significantly less useful.

**Comment by PavelVozenilek** [comment]
Well, being "no return" is not something of utmost importance. I guess the annotation is to shut up the compiler from complaining, and the old good assert would be good enough for this..

**Comment by lerno** [comment]
It is also a contract for external analysis.

**Comment by lerno** [comment]
Usage are different, so unless there are other arguments for removing no return it will be retained.

**Comment by lerno** [comment]
I'll close this one as there seems to be no additional arguments for.
