### ISSUE TITLE
inline attribute

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#4]
The thing I dreamed about was ability to inline _part_ of a function:

```
void foo(void* p)
{
   if (!p) {
    return;  // this is the fast path
   }

   ... // the slow complex path, taken infrequently
}
```

would look e.g. like:

```
void foo(void* p)
{
inline: // this part gets inlined
   if (!p) {
    return;  // this is the fast path
   }

noinline: // this part is not inlined
   ... // the slow complex path, taken infrequently
}
```

The compiler could check against wrong use.

**Comment by lerno** [comment]
I don't understand what sort of code you imagine this would generate.

**Comment by PavelVozenilek** [comment]
I imagine it would transform this:

```
void bar()
{
  void* p = ...
  foo(p);
}

void foo(void* p)
{
inline:
   if (!p) {
    return;
   }

noinline: 
   ... // the complicated part
}
```

to:


```
void bar()
{
  void* p = ...
  if (!p) {
   } else {
     foo(p);
  }
}

noinline:
void foo(void* p)
{
 ... // the complicated part
}
```

The compiler could/should refuse to deal with _too complex_ inlined function parts, which would act as protection against misuse.

------------


One practical example: array's append function. At the beginning it would check whether array needs to be resized. If not, it would add the new value and return. This part could be inlined.

```
void array-append(array* a, int value)
{
inline:
  if (a.capacity > a.size) {
    array.data[array.size++] = value;
   return;
  }
noinline:
   ... // reallocate the array
}
```

--------------

The syntax could also replace the annotation:

```
inline:
func void foo() {} // must inline

no-inline:
func void bar() {} // won't inline
```

**Comment by lerno** [comment]
If so, then this: 
```
void bar()
{
  void* p = ...
  foo(p);
}

void foo(void* p)
{
inline:
   if (!p) {
    return;
   }

noinline: 
   ... // the complicated part
}
```

Can be replaced by this:
```
void foo(void* p) @inline
{
   if (!p) {
    return;
   }
   realloc_something(...)
}
```

So it's syntactic sugar to avoid having to do the splitting by hand?

**Comment by PavelVozenilek** [comment]
Splitting a function may not be the most desirable design. It would create yet another named entity, reason for its existence wouldn't be crystal clear, there would be temptation to invoke this helper in wrong context, functionality would be separated into two parts.

The `inline`/`noinline` expresses exactly what it aims for, with no other changes in the code.

**Comment by lerno** [comment]
Your example is one with a clear split that follows the general flow of the function.

Do you only envision this sort of split (which would be rather specialized) or do you have a more general functionality in mind (in which case it would seem rather complex to implement)

**Comment by PavelVozenilek** [comment]
I do not have any generalizing in my mind.

In absence of C macros this could be used to support efficient implementation of logging, debug support etc.

```
void do_log(string s)
{
inline:
  if (!logging_enabled_flag) {
    return;
  }
no-inline:
   printf(...);  
}
```

If the value of `logging_enabled_flag` is known at compile time as false, the compiler may throw away the whole invocation, including the overhead of creating string parameter. Just like with a macro.

```
const logging_enabled_flag = false;

void bar()
{
  do_log("xyy"); // will turn to no-op
}

```

Technically, the compiler could do this optimization w/o `inline` hints, but it feels that it would be easier  if only the small inlined part of the code is involved in the decision.

-----------

There's one _over-engineered_ feature possible with `inline`/`no-inline`. When the developer is really into performance and wants to do "manual profile-guided optimization".


```
func void foo()
{
inline:
   ...
no-inline:
  ...
}

TEST(profile-guided-optimize=foo)
{
  .. // prepare data for foo
  foo();
}
```

If the compiler understands what we want, it would generate two `foo` functions, one observing inline hint, then another ignoring it and not inlining anything. Then it would clone the test into two, each calling its `foo` version. Precise timing of both tests would be recorded somewhere, and the faster variant selected for the release.

This is however something super-advanced, rarely needed, with only minor benefit.

**Comment by lerno** [comment]
I can't see enough of benefit of this in the general case that couldn't be solved by manually coding it in the few places where it's necessary.

**Comment by lerno** [comment]
This feature does not seem to be sufficient to warrant the added complexity to the language. Since the language should not grow too large the benefit would have to be bigger.

Are there any additional benefits not mentioned above (or arguments for?) otherwise I think I need to reject this feature.

**Comment by lerno** [comment]
No additional arguments have been forthcoming.
