### ISSUE TITLE
named arguments

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#5]
The docs shows an example:

```
func void testNamed(int times, double data)
{
    for (int i = 0; i < times; i++)
    {
        printf("Hello %d\n", i + data);
    }
}

func void test()
{
    testNamed(data = 3.0, times = 1)
    testNamed(3, 4.0);
}
```

Perhaps it is just a mistake, but it shows named parameters in different order than declared. IMO this is invitation for bugs and confusion.  The order of parameters is clearly specified, any "freedom" here makes things worse for no gain.

**Comment by lerno** [comment]
I will consider it.

**Comment by lerno** [comment]
I have solicited feedback in regards to this, and the unanimous opinion seems to be that reordering is desirable. So unless there are some great arguments for this I'll reject it.

**Comment by lerno** [comment]
Closed.
