### ISSUE TITLE
versatile constraints for structs

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#6]
Structure members could have attached constraints, using the good old `assert` understood by the compiler. 

```
struct S
{
  void* ptr;   assert(ptr != 0); //non-null constraint
}
```

The compiler would check against explicit assignment of `0`, and also insert the `assert` after every change of the `ptr` struct member.

---------------

```
struct S
{
  int i;      assert(i > 0 && i < 10);   // range constraint
  int j;      assert(j == 0 || j == -2); // enumeration constraint
  double d;   assert(sqrt(d) < 1.0);     // more complicated constraint
}
```

------------
The constraint could deal with the whole structure:

```
struct S
{
  int i; 
  int j; assert(i < j); // i and j are names looked up first in the struct scope
}
```

------------

The compiler would insert `assert`s involving multiple struct members at the end of function scope:

```
struct S
{
  int i; 
  int j; assert(i < j); 
}

void foo()
{
  struct S s;

  s.i = 1; 
  // no assert yet

  s.j = 0; 
  // no assert yet
  for (int i = 0; i < 10; ++i) {
    s.j += 1; 
    // no assert yet
  }
  ...
  assert(s.i < s.j); // inserted by the compiler HERE
}
```

The `assert` would be also inserted at the end of scope where the struct lifetime ends (to protect short lived structures)

------------

The compiler could automatically convert simple `assert` into more informative one:

```
struct S
{
  int i; 
  int j; assert(i < j);
}
```

would morph into:

```
struct S
{
  int i; 
  int j; assert(i < j | i = $i, j = $j);
}
```
----------------

There could be special "traits" named `old` and `new` for use in constraints:

```
struct S
{
  int i;  assert(new.i >= old.i); // the value may not decrease
}
```

-----------------

Restrictions on reassignement are possible:

```
struct S
{
  bool b;  assert(new.b == false); // only false can be assigned AFTER initialization
}
```

Here the initial value of `b` could be anything. However, any later assignment (later as not inside the function which initialized it) would be checked by `assert`. The check would be also inserted where lifetime of the struct ends.

--------------

It may be possible to limit reassignement to a literal:

```
struct S
{
  bool b = true;  assert($new.b == false); 
}
```
Here the inital value is always `true`, any reassignement has to be `false` and it needs to be known at compile time (that's the `$` in front of `$new`). 

This example would implement "flag type", restricted boolean which could only be reset from its initial value.

-----------------

Flip-flop constraint:

```
struct S
{
  bool b;  assert(new.b != old.b);
}
```

Flip-flop constraint with literals only:

```
struct S
{
  // $old.b means that even initialization has to be by a literal
  bool b;  assert($new.b != $old.b);  
}
```

-----------------

Non-mutability constraint after initialization could be also implemented this way. It is somehow clumsy, though. This would need compiler support to be enforced.

```
struct S
{
  bool b;  assert(new.b == old.b);
}

void foo()
{
  struct S s;
  s.b = (x > 0) ? true : false;
  bar(&s); // inside bar() further modification of s.b is not allowed
  s.b = baz(); // not allowed
}
```

This would implement "constant values initialized at runtime".

**Comment by lerno** [comment]
It is an interesting idea, but syntax needs to be simplified and streamlined.

**Comment by lerno** [comment]
I need a simplified proposal for this or it will be rejected.

**Comment by lerno** [comment]
No proposal has been forthcoming
