### ISSUE TITLE
type deduction

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#7]
Modern C++ did one thing right: they reused `auto` keyword for type deduction for a local variable:

`auto x = foo();
`

But they still overcomplicated the thing with annotations like:

`const auto x& = foo();
`

----------------

C3 could have type inference too, w/o these complications:

`x = foo();
`

or, if the parser needs a hint (which I suspect):

`auto x = foo();
`

People who know C++ would be instantly familiar with it.

Java uses `var`, also reasonable option.

------------

There should be limit where one could use this feature: if there's absolutely no implicit conversion, ambiguity or doubt:

1. Assignment of function result:

    `      auto x = foo();
    `

2. Simple assignment of another value:

```
    some-long-name x = ...
    auto y = x;
    auto z = &x; // non-null pointer

```

3. Expression if when there's no conversion:

`    auto x = (y > 0) ? true : false;
`

---------------

Anything more complicated would still need explicit type:

```
// These would not compile:
auto x = foo() + 1; // potential conversion here, currently underspecified
auto x = y + z; // ditto
auto x = 1; // literal type is not specified, AFAIK
auto x = (y < 0) ? 1 : 1.2; // conversion here
```
If the language behavior gets ironed out, some may be enabled.

----------------

About `*` and `&` pointers: this information is already present in the code or is deductible, it needs not to be repeated.

Non/nullness is something what compiler could track easily (unlike, say, valid integer range), and can could be inferred and propagated from `assert(ptr != 0)` statements and from ordinary null handling code.

------------

Having type inference for function results would allow further simplification of the language later.

**Comment by lerno** [comment]
Type inference is a code smell. Types should be sufficiently short that type inference is unnecessary.

**Comment by PavelVozenilek** [comment]
Heh, if that only works. People have tendency to invent descriptive names and consider them as a great accomplishment. Sometimes names are forced externally (e.g. in SCADA systems).  Library authors preemptively use long names to make them unique.

**Comment by lerno** [comment]
typedef is your friend. Long names for uniqueness is not necessary with nested namespaces.

**Comment by lerno** [comment]
Since this type inference is an anti-feature of C3. I will close this feature.
