### ISSUE TITLE
function name overloading

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3docs#8]
Here I argue  in favor of function name overloading in C3.

-----------

C does'use it. The reasons are historical, very limited memory and expectation of only thousands of lines of code for a typical project. It is not a problem to invent unique name in such situation.

As codebases grew up, people reacted by inventing very, very long structures names to keep possibility of name collisions low.  Some code (zlib) uses macros to allow renaming.

I see this approach as failure.

---------------

 The arguments (and counterarguments) against function name overloading:

* It is complicated.  - Inventing artificial names to avoid collision complicates things more.
* Needs better tools. - Yes, grep and ctags are not enough.
* Overloading rules are complicated. - Not if there's no implicit conversion.
* It is easy to accidentally make a mess. - Not if there's no implicit conversion. 

--------------
The arguments for function name overloading:

* It reduces pressure to invent new global names. This is something overlooked, as if it is nothing to care about. Inventing name and remembering is hard and stressing.
* It models the world better. `log` is decimal logarithm and `log` is the natural name for logging function. Invent new name and you have to remember one more unnatural thing.
* Overloading reduces the need (and temptation) to use fully qualified names, prefixed with module or namespace. Especially if there is implicit import of everything else in the project.

---------------

What should _not_ be supported:

* Any kind of implicit conversion. Just because `operator +` or `sin()` may use both integers and floats doesn't justify complexification of the language. Manually overload these math function for all possible combinations. 
* The C11 approach with `_Generic`. This is ugly and hard to do. If you want to overload 1 function with 1 another type, you end up with 3 global names.
* Overloading based on just type annotation (e.g. pointer (non)null-ness). Such annotations are much less visible then the type itself.

**Comment by lerno** [comment]
A clear *no* to function overloading. C3 will support something like it with:

1. Method functions (associating a function with a type)
2. Generic functions
3. Extension of generic functions

**Comment by lerno** [comment]
1. Overloading of `log` is done using generic functions if desired.
2. Usually what we want is actually not a complete lack of namespace, many times we want the some form of namespace. `Player::logIn(username, pw)` `Admin::login(username, pw)` `ApiUser::login(username, pw)` just using `login` is deeply insufficient.

With polymorphic functions the need for overloading is practically none.

I would need more arguments to even ponder this.

**Comment by lerno** [comment]
I will reject this since no more arguments are forthcoming in favour of it.
